---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/abstract-art-cologne.md
- projects/bigger-is-better-burning-windows.md
- projects/brandhalle-utopia-stadt-nordbahntrasse-wuppertal.md
- projects/express-yourself.md
- projects/love-urban-art-spray-hands.md
- projects/painted-pixels.md
- projects/stairways.md
